### ISSUE TITLE
How to integrate in build / derivation

### ISSUE THREAD

**Issue by ChrisOboe** [danielbarter/mini_compile_commands#2]
Hi, 

if i understood the readme correctly mini_compile_commands is used somewhat interactively. a mini_compile_commands server needs to be manually started bevor it works. 

This works fine in a shell when manually building the software, but instead of creating the compile_commands "manually" I'd prefer to create it automatically while building a derivation (through a nix build).  

i couldn't get mini_compile_commands_server running properly during building a derivation. (I assume running processes just get killed by nix when the building phase switches to the next one). 

Is there currently a way to get this working?

**Comment by danielbarter** [comment]
Hi @ChrisOboe: 

This should be possible using the appropriate hooks. For example, if you add 
```
mini_compile_commands_server.py & # spawn the server
MINI_COMPILE_COMMANDS_PID=$! # record the PID of the spawned server
sleep 1 # python is kind of slow to start up
```
as a pre build phase and 
```
kill -s SIGINT $MINI_COMPILE_COMMANDS_PID # send SIGINT to the server
```
as a pre install phase, then a `compile_commands.json` will be generated, which you can move into place during the install phase. I think it would be hard to do in general, but for any specific derivation it should be possible! 

Incidentally, this is pretty much how the tests work. I don't think that `${stdenv}/setup` kills processes between phases, but i am not 100% sure.

**Comment by danielbarter** [comment]
yep, this works. I wrote an example derivation: https://github.com/danielbarter/mini_compile_commands/blob/main/tests/build/hook.nix

I need to run now, but will add a section to the README for this tomorrow.

**Comment by danielbarter** [comment]
OK, I have implemented this. Now you can generate a `compile_commands.json` file using `nix-build` like this:
```
with import <nixpkgs> {};
let mcc-env = (callPackage <this_repo> {}).wrap stdenv;
    mcc-hook = (callPackage <this_repo> {}).hook;
in (hello.override { stdenv = mcc-env; }).overrideAttrs
  (finalAttrs: previousAttrs: {
    buildInputs = (previousAttrs.buildInputs or []) ++ [ mcc-hook ];
  })
```
keep in mind that `compile_commands.json` entries have a `directory` attribute which is the absolute path from which the compile invocation occurred, so the generated json files will only work if you store your source code in the same place as the nix builder, which is kind of inconvenient. 

All explained in the README, so going to close this as finished. Thanks @ChrisOboe!

**Comment by hustlerone** [comment]
And for doing this in nix-shell? I use arrterian.nix-env-selector and I would like to not have to do manual work every single time I open codium
