### ISSUE TITLE
`compile_commands.json` is not generate - what am I doing wrong?

### ISSUE THREAD

**Issue by cgahr** [danielbarter/mini_compile_commands#6]
Thank you very much for this package, it works, but I think I'm doing something wrong. For some reason, when I execute `nix shell .`, `compile_commands.json` is not generated. My setup is as follows:
```nix
# flake.nix
{
  description = "A very basic flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";

    mini-compile-commands = {
      url = "github:danielbarter/mini_compile_commands";
      flake = false;
    };
  };

  outputs = { self, nixpkgs, mini-compile-commands }:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages."${system}";
      mcc-env = (pkgs.callPackage mini-compile-commands { }).wrap pkgs.stdenv;
      mcc-hook = (pkgs.callPackage mini-compile-commands { }).hook;
    in
    {
      packages."${system}" = {
        slstatus = pkgs.slstatus.overrideAttrs (old: {
          src = ./.;
          buildInputs = old.buildInputs;
        });

        slstatus_dev = (self.packages."${system}".slstatus.override {
          stdenv = mcc-env;
        }).overrideAttrs (finalAttrs: previousAttrs: {
          buildInputs = (previousAttrs.buildInputs or [ ]) ++ [ mcc-hook ];
        });

        default = self.packages."${system}".slstatus;
      };

      devShells."${system}" = (pkgs.mkShell.override { stdenv = mcc-env; }) {
        # slstatus = (pkgs.mkShell.override { stdenv = mcc-env; }) {
        pname = "slstatus";
        version = "1.0";
        src = ./.;
        preBuild =
          ''
            makeFlagsArray+=(LDLIBS="-lX11 -lxcb -lXau -lXdmcp" CC=$CC)
          '';

        nativeBuildInputs = [ pkgs.pkg-config ];
        buildInputs = with pkgs; [ libX11 libXau libXdmcp ];

        installFlags = [ "PREFIX=$(out)" ];
      };
      #   default = self.devShells.x86_64-linux.slstatus;
      # };
    };
}
```
The results are as follows:
- `nix build .` and `nix build .#slstatus`: the `result` folder does not contain `compile_commands.json` (as expected)
- `nix build .#slstatus_dev`: the `result` folder contains `compile_commands.json` but (as far as I understand) the paths in it point to the wrong folder (as expected)
- `nix shell .`: `slstatus` is correctly compiled and runs, however, `compile_commands.json` is not generated/is not in the current directory (unexpected)

Altogether, I think I did ~90% right, judging by `compile_commands.json` being generated with `nix build .#slstatus_dev`. However, something is wrong with my shell definition. Can you help me?

**Comment by danielbarter** [comment]
When you spawn a dev shell, no building actually happens (so no compiler invocations occur). It puts you into an environment where you can build your project

In you dev shell, if you launch the mini compile commands server and then build your project, a `compile_commands.json` will be created
